#!/usr/bin/gawk -f
#Author: Max Gambee
#email: max.a.gambee@gmail.com
#This script compares all of the files passed in as arguments, and outputs to std
BEGIN{
	for(i=1;i<ARGC;i++) {
		files[i] = ARGV[i];
	}
	for(i in files) {
		print files[i];
	}
}
